[project]
name = "gesture"
version = "0.1.0"
description = "A virtual drawing application using computer vision"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python",
    "numpy",
    "mediapipe",
    "pyautogui",
]
